=== LucaMorazzano/VideoGames/recensioni.dtd
<!ELEMENT recensioni (recensione+)>
	<!ELEMENT recensione (username, valutazione, testo)>
	<!ELEMENT username #PCDATA>
	<!ELEMENT valutazione 1|2|3|4|5 (#PCDATA)>
	<!ELEMENT testo #PCDATA>

=== LucaMorazzano/VideoGames/recensioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE telefoni SYSTEM "recensioni.dtd">
<recensioni><recensione><username>Luca</username><valutazione>3</valutazione><testo>okay</testo></recensione><recensione><username>Luca</username><valutazione>5</valutazione><testo>ok</testo></recensione><recensione><username>Luca</username><valutazione>2</valutazione><testo>Mi aspettavo di più</testo></recensione><recensione><username>Luca</username><valutazione>2</valutazione><testo>Mi aspettavo di più</testo></recensione><recensione><username>Luca</username><valutazione>5</valutazione><testo>Ottima organizzazione </testo></recensione><recensione><username>Andrea</username><valutazione>4</valutazione><testo>Vasta gamma di prodotti di ottima qualità </testo></recensione></recensioni>
